version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/image_scraper
      - JWT_SECRET=your_jwt_secret_key
      - PIXABAY_API_KEY=your_pixabay_api_key_here
    depends_on:
      - mongo
    volumes:
      - ./public:/app/public

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
